---
title: "Selected Presentations"
output: html_document
---


- Invited and Contributed Conference Talks

    - 59th Actuarial Research Conference,July 2024- “Causality-based feature selection and application to insurance analytics.”
    - 57th Actuarial Research Conference,Aug 2022- “Ratemaking in a Changing Environment.”
    - 25th International Congress on Insurance: Mathematics and Economics, July 2022- “Ratemaking in a Changing Environment.”
    - 56th Actuarial Research Conference, Aug 2021- “Loss Data Analytics: Short Course”, with Edward Frees. 
    - 24th International Congress on Insurance: Mathematics and Economics. July 2021- “Individual-Level Loss Reserving and Environmental Changes.”
    - 54th Actuarial Research Conference, Aug 2019- “Joint Models for Individual-Level Loss Reserving.”
    - American Risk and Insurance Association (ARIA) Annual Meeting, Aug 2019- “Joint Models for Individual-Level Loss Reserving.”
    - Western Risk and Insurance Association Annual Meeting, Jan 2016- “Using Machine Learning to Flag Workers’ Compensation Insurance Companies at Risk of Insolvency” with James Jones.
    - St.John’s University/JII symposium, Oct 2015- “Drought Triggered Index Insurance Using Cluster Analysis of Rainfall Affected by Climate Change,” with Asker Choudhury, James Jones and Raquiba Choudhury.



- Colloquium & Seminar/Webinar Talks

    - ASTIN Webinar with Edward Frees, Zeinab Amin, Brian Hartman, Rajesh Sahasrabuddhe, Ronald Richman, and Eric Dal Moro, Apr 2025- “Actuarial Fundamentals & Loss Data Analytics Webinars.”
    - UNC Charlotte, Dept. of Mathematics and Statistics Seminar, Sept 2024- “Ratemaking in a Changing Environment.”
    - ASTIN Webinar, Sept 2022- “Ratemaking in a Changing Environment.”
    - The Australia National University, Research School of Finance, Actuarial Studies and Statistics Seminar, May 2022- “Ratemaking in a Changing Environment.”
    - Appalachian State University, Mathematics Department Colloquium, Apr 2022- “Ratemaking in a Changing Environment.”
    - Bentley University, Mathematics Department Colloquium, Dec 2021- “Individual-Level Loss Reserving and Environmental Changes.”
    - ASTIN Webinar, Nov 2020- “Joint Model Prediction and Application to Individual-level Loss Reserving” with Peng Shi and Edward Frees
    - Huebner Doctoral Colloquium at ARIA, Aug 2019- “Joint Models for Individual-Level Loss Reserving.”






* * *