---
title: ""
output: html_document
---




**Publications**

[Google Schorlar Citation](https://scholar.google.com/citations?hl=en&view_op=list_works&authuser=4&gmla=AJsN-F4eRynE1IvRTW46-MS8qvAAvRJnUU0ZuvA6140jGwI97f0sUV9QouuoAGSLZdv1W710kRgDkOUoDtMIZjPqZ3lgFBnO6d3n3AxRWszH7pnND2mAcxc&user=rSJIHZ0AAAAJ)

* Marland, E., Baldwin, A., Beecher, A., D'Andrea, J., Erickson, K., Hartling, K., McMorris, D.,Mendiratta, V., Okine, A. N., & Pinzon, K. (2024). Judges' commentary: Sustainability in property insurance. UMAP Journal, 45(3), Fall 2024 Edition.

* Okine, A. (2023). Ratemaking in a changing environment. ASTIN Bulletin: The Journal of the IAA, 1-23. doi:10.1017/asb.2023.23

* Okine, A.N (2022). Okine, A. Nii-Armah. 2023. “Individual-Level Loss Reserving and Environmental Changes.” Variance 16 (1)

* Okine, A.N, Frees, E., Shi, P. (2021). Joint model prediction and application to individual-level
      loss reserving. ASTIN Bulletin. Published Online Nov. 5th, 2021. 

* Choudhury, A., Jones, J., Okine, A. and Choudhury, R. (2016). Drought Triggered Index    
   Insurance Using Cluster Analysis of Rainfall Affected by Climate Change. Journal of Insurance Issues,   
   Vol 39:2, pp 169-86.


**Book Chapter/Open Educational Resources**

* Frees, E. W., Okine, A. N.  and  Saridas, E. S. (2023). Quantifying Dependence. In Loss Data    
   Analytics (2nd ed.) Retrieved from https://openacttextdev.github.io/LDA_Ed2/

* Higgins, T., Huang F., Okine, A. N.,  Sahasrabuddhe, R. (2021). Modeling Loss Severity. In Loss Data Analytics: Short Course.  Retrieved from https://openacttextdev.github.io/LDACourse1/

* Frees, E. W., Okine, A. N.  and  Saridas, E. S. (2019). Dependence Modeling. In Loss Data    
  Analytics. Retrieved from https://ewfrees.github.io/Loss-Data-Analytics




**Other Research:**

* Joint research with members of the International Association of Black Actuaries (IABA): "Assessment of IABA's Scholarship & Boot Camp Programs: An Empirical Analysis," 2019


**Grants:**

* Lee, G. and Okine, A.N. (2025). Casualty Actuarial Society, Individual Grant Competition. $15,000
    Title of Project: Loss reserving with textual description of claim
    Role: Co-principal investigator

* Okine, A.N. (2022). CAS Research/Proposal Development Summer Grant. $5,000
    Title of Project: Ratemaking in a Changing Environment
    Role: Principal investigator

* * *